---
on: [push, pull_request]
name: Lint
jobs:
  rstcheck:
    name: Validate rst
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            sudo apt-get install python3-setuptools
            sudo python -m pip install --upgrade pip
            sudo pip install rstcheck

      - name: run rstcheck
        run: rstcheck --report-level error *.rst
